Introduction/personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<int:pk>/", views.blog_detail, name="blog_detail"),
    path("<category>/", views.blog_category, name="blog_category"),
]

Introduction/personal_portfolio/contactus/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "contactus"
urlpatterns = [
     url('', views.contact_us_view, name='contact_us'),
]

Introduction/personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include("projects.urls")),
    path('blog/', include("blog.urls")),
    path('contact_us/', include("contactus.urls")),
]

Introduction/personal_portfolio/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.project_index, name="project_index"),
    path('<int:pk>/', views.project_detail, name="project_detail"),
]

Introduction/personal_portfolio/blog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    """docstring for Category."""
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class Post(models.Model):
    """docstring for Post."""
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')   # Many categories can be assigned to many posts.

    def __str__(self):
        return self.title

class Comment(models.Model):
    """docstring for Comment."""
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)  #One post can have many comments

    def __str__(self):
        return self.author
    def __str__(self):
        return self.body

Introduction/personal_portfolio/contactus/models.py
from django.db import models

# Create your models here.
class ContactUs(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name + "-" +  self.email

Introduction/personal_portfolio/projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    """docstring for Project."""
    title = models.CharField(max_length = 100)
    description = models.TextField()
    technology = models.CharField(max_length = 25)
    image = models.FilePathField(path = "/img")

    def __str__(self):
        return self.title

Introduction/personal_portfolio/blog/forms.py
from django import forms

class CommentForm(forms.Form):
    """docstring for CommentForm."""
    # forms.TextInput widget tells Django to load this field as an HTML text input element in the templates
    author = forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Your name"
        })
    )
    # forms.TextArea widget instead, so that the field is rendered as an HTML text area element.
    body = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Leave a comment!"
        })
    )

Introduction/personal_portfolio/contactus/forms.py
from django import forms


class ContactForm(forms.Form):
    name= forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Your name"
        })
    )
    email= forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Your email"
        })
    )
    subject= forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Subject"
        })
    )
    message=forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Enter your message here"
        })
    )

Introduction/personal_portfolio/blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from .forms import CommentForm
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts,
    }
    return render(request, "blog/blog_index.html", context)

def blog_category(request, category):
    posts = Post.objects.filter(categories__name__contains=category
    ).order_by('-created_on')
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "blog/blog_category.html", context)

def blog_detail(request, pk):
    post = Post.objects.get(pk = pk)
    # Loading form
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author = form.cleaned_data["author"],
                body = form.cleaned_data["body"],
                post = post
            )
            comment.save()
            return HttpResponseRedirect('')
    comments = Comment.objects.filter(post = post)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog/blog_detail.html", context)

Introduction/personal_portfolio/contactus/views.py
from django.shortcuts import render
from .forms import ContactForm
from contactus.models import ContactUs
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import mail_admins
from django.contrib import messages

def contact_us_view(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Saving mail in the database
            msg = ContactUs(
                name = form.cleaned_data['name'],
                email = form.cleaned_data['email'],
                subject = form.cleaned_data['subject'],
                message = form.cleaned_data['message'],
            )
            msg.save()
            # Sending mail to admins
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = "You have a new message from {}:{}".format(name, email)
            message = "Subject: {}\n\nMessage: {}".format(form.cleaned_data['subject'], form.cleaned_data['message'])
            mail_admins(subject, message)
            messages.add_message(request, messages.INFO, 'Mail sent.')

            return HttpResponseRedirect('')
    else:
        form = ContactForm()

    context= {'form': form}
    return render(request, 'contact_us/contact.html', context)

Introduction/personal_portfolio/projects/views.py
from django.shortcuts import render
from projects.models import Project

# Create your views here.
def project_index(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'projects/project_index.html', context)

def project_detail(request, pk):
    project = Project.objects.get(pk = pk)
    context = {
        'project': project
    }
    return render(request, 'projects/project_detail.html', context)

Introduction/personal_portfolio/blog/templates/blog/blog_category.html
{% extends "personal_portfolio/base.html" %}
{% block page_content %}

<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>

    {% for post in posts %}
        <h2><a href="{% url 'blog:blog_detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;Categories:&nbsp;

            {% for category in post.categories.all %}
            <a href="{% url 'blog:blog_category' category.name %}">{{ category.name }}</a>&nbsp;
            {% endfor %}

        </small>
        <p>{{ post.body | slice:":400" }}...</p>

    {% endfor %}

</div>

{% endblock %}

Introduction/personal_portfolio/blog/templates/blog/blog_detail.html
{% extends "personal_portfolio/base.html" %}
{% block page_content %}

<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>

    <small>
        {{ post.created_on.date }} |&nbsp;Categories:&nbsp;

        {% for category in post.categories.all %}
        <a href="{% url 'blog:blog_category' category.name %}">{{ category.name }}</a>&nbsp;
        {% endfor %}

    </small>

    <p>{{ post.body | linebreaks }}</p>

    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <h3>Comments:</h3>
    {% for comment in comments %}
      <p>
          On {{comment.created_on.date }}&nbsp;
          <b>{{ comment.author }}</b> wrote:
      </p>
      <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}

</div>

{% endblock %}

Introduction/personal_portfolio/blog/templates/blog/blog_index.html
{% extends "personal_portfolio/base.html" %}
{% block page_content %}

<div class="col-md-8 offset-md-2">
    <h1>Oreon Index</h1>
    <hr>

    {% for post in posts %}

    <h2><a href="{% url 'blog:blog_detail' post.pk %}">{{ post.title }}</a></h2>

    <small>
        {{ post.created_on.date }} |&nbsp; Categories:&nbsp;

        {% for category in post.categories.all %}
        <a href="{% url 'blog:blog_category' category.name %}">{{ category.name }}</a>&nbsp;
        {% endfor %}

    </small>

    <p>{{ post.body | slice:":400" }}...</p>

    {% endfor %}
</div>

{% endblock %}

Introduction/personal_portfolio/contactus/templates/contact_us/contact.html
{% extends "personal_portfolio/base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h1>Contact Us </h1>
    <hr>

    <p><form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
  </form></p>
</div>

{% endblock %}

Introduction/personal_portfolio/personal_portfolio/templates/personal_portfolio/base.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:project_index' %}">Oreon Inc.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:project_index' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:blog_index' %}">Blog</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'contactus:contact_us' %}">Contact us</a>
            </li>
          </ul>
        </div>
    </div>

</nav>

{% block page_content %}{% endblock %}

<hr>
<!-- Footer -->
<footer class="page-footer font-small mdb-color pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Company name</h6>
        <p>Oreon</p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
        <p>
          <a href="#!">Mobile Apps</a>
        </p>
        <p>
          <a href="#!">Desktop Apps</a>
        </p>
        <p>
          <a href="#!">Websites</a>
        </p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
        <p>
          <a href="#!">Python Course</a>
        </p>
        <p>
          <a href="#!">Machine Learning Tutorials</a>
        </p>
        <p>
          <a href="#!">Hadoop Tutorials</a>
        </p>
        <p>
          <a href="#!">Tablea Tutorials</a>
        </p>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
        <p><i class="fas fa-home mr-3"></i> Murang'a, Kenya</p>
        <p><i class="fas fa-envelope mr-3"></i> oreonincorporated@gmail.com</p>
        <p><i class="fas fa-phone mr-3"></i> +254 705 38 58 94</p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Footer links -->

    <hr>

    <!-- Grid row -->
    <div class="row d-flex align-items-center">

      <!-- Grid column -->
      <div class="col-md-7 col-lg-8">

        <!--Copyright-->
        <p class="text-center text-md-left">© 2020 Copyright:
          <a href="#"><strong>oreoninc.org</strong></a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 ml-lg-0">

        <!-- Social buttons -->
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">

                <i class="fab fa-twitter"><img src="{% static 'img/twitter.png' %}"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

Introduction/personal_portfolio/projects/templates/projects/project_detail.html
{% extends "personal_portfolio/base.html" %}
{%  load static %}

{% block page_content %}
<h1>{{ project.title }}</h1>
<div class="row">

  <div class="col-md-8">
    <img src="{% static project.image %}" alt="" width="100%">
  </div>

  <div class="col-md-4">
    <h5>Our service:</h5>
    <p>{{ project.description }}</p>
    <br>
    <h5>Technology used:</h5>
    <p>{{ project.technology }}</p>
  </div>

</div>
{% endblock %}

Introduction/personal_portfolio/projects/templates/projects/project_index.html
{% extends "personal_portfolio/base.html" %}
{% load static %}
{% block page_content %}

<h1>Our Work</h1>

<div class="row">
  {% for project in projects %}

    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">Read More</a>
            </div>
        </div>
    </div>

  {% endfor %}
</div>

{% endblock %}